language: python

python:
 - "3.5.2"

services:
  - postgresql

addons:
  - postgresql: "11.2" 

before install:
  - sudo apt-get update

install:    
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coveralls


before_script:
  - psql -c 'create database flocka_records;' -U postgres
 
script:    
  - pytest app/api/tests
  - coveralls

after_success:
  - coveralls