language: python

python:
 - "3.5.2"

services:
  - postgresql

before_script:
  - psql -c 'create database flocka_records;' -U postgres

install:    
- pip install -r requirements.txt
- pip install pytest-cov
- pip install coveralls

script:    
- pytest --cov=app/api/tests
- coveralls
after_success:
- coveralls
