language: python

python:
 - "3.7.3"

services:
  - postgresql

addons:
  postgresql: "11.2" 

before_script:
  - psql -c "CREATE DATABASE flocka_records;" -U postgres

install:    
- pip install -r requirements.txt
- pip install pytest-cov
- pip install coveralls

script:    
- pytest --cov=app/api/tests
- coveralls
after_success:
- coveralls